### ISSUE TITLE
[TODO] Buildings

### ISSUE THREAD

**Issue by tannerflick4** [Altemio/SevenKingdoms-master#10]
Making this to mainly just note what I have added so far. 

Uniques: Moat Cailin, The Wall, Casterly Rock, Ironwood Forest, Storm's End, Starfall, various shipyards.

Regular: Wildling barrack (4 levels)

Cultural: Pentoshi, Myr, Tyrosh

DONT ADD: The Eyrie, Red Keep, Twins, Harrenhal, dragonstone specials, Summerhall. These were not constructed yet, and should be added in later as something you or the AI can build up to.

I'll update this issue with any things I add and buildings I find that haven't been constructed yet but are in the times the show covers.

**Comment by ZeroFighterR** [comment]
Added: Winterfell, Dreadfort, Wolfswood, Greatbarrow, Smallbarrow, castamere, riverrun, hightower, kingswood, rainwood, hammerhorn mine, marcher castles and duskendale

**Comment by tannerflick4** [comment]
Great!

**Comment by RowanMaBoot** [comment]
We can add un-built unique structures, but we should make their requirements kinda harsh or difficult. Some, like Harrenhall and the Red Keep presumably should require the highest settlement level constructed, which will be expensive and time consuming. I think we may also be able to restrict the date of construction too, maybe.

Others may require unique culture combinations. I don't know who built Sunspear, or when, but I'll make a guess as an example.

So, the province is Dornish but if you have a Rhoynar ruler they should be able to build it. As the Rhoynar culture does not natively exist from the start, it means the only way Sunspear may be built is if the player is a ruler designed character or if it is post-invasion.

**Comment by RowanMaBoot** [comment]
TODO:

**City Specific**
- Fishing Docks, tied to city level, coastal restricted construction
- Districts; Trade District, required for higher level markets; Slum district, improves LI amount, tax income but has big RR increase; Religious district, provides piety to liege and barony owner, tax income, tied directly to city level, minimum required is city. Buildings beyond city level require districts, markets may upgrade into districts at highest levels.

**Castle Specific**
- Hamlets, minor outlying villages, tied to castle town level
- Castle town tree, tied to settlement level
- Fishing hut, tied to hamlets

**Tribal Specific**
- Settlement levels, up to ~6 levels

**Comment by Vierwood** [comment]
Also when you make a unique building like Winterfell, don't forget to actually place it in the game. As in make sure it has been built when we start the game.

**Comment by RowanMaBoot** [comment]
I've finished with castles/towns for now. If any values need buffing, like money income, let me know. I've kinda  been on the safe side with levy and income, keep very close to vanilla values.

**Comment by tannerflick4** [comment]
@blackninja9939 - I would like some advice on coding for cultural buildings. Which one is best to use?

potential = {
 			location = {
 				OR = {
 					culture = iron_islander
 				}
 			}
 		}

or

potential = {
			FROM = { culture = ethiopian }
		}

Also, I am interested in (much later) adding a persistent nature to these buildings. Where the player or AI would have to start building another culture's buildings before the old culture's buildings would be got rid of.

**Comment by RowanMaBoot** [comment]
Not blackninja, but I kind of cover it in one of the files, but it might be kind of obscure. The effects of the two are drastically different, and the former:

`
potential = {
    location = {
        culture = [culture]
    }
}
`

Means a building can be built in any province of that culture, regardless of the culture of the ruler. In most cases, this is probably what you will want.

`
potential = {
    FROM = { culture = [culture] }
}
`

That block of code checks the ruler of the county itself. If they're that culture, you will be able to build that building in any province so long as **you** remain that culture.

If your culture changes to one not required to build that building (or the province is taken by someone not of the required culture), the buildings are lost forever and will have to be rebuilt if you revert back to the right culture or retake the province.

`
potential = {
    location = {
        culture = [culture]
    }
    FROM = { culture = [culture] }
}
`

I've used this for a couple of buildings, such as pirate buildings, which I only want pirates to use. This also has the added effect of only allowing pirates to build pirate buildings in the Stepstones themselves, which helps balance the structure and their effects.

Furthermore, it helps prevent issues related to a culture getting exceptionally strong buildings. The Stepstone structures are really strong province for province, and having an Arbor or Dorne taking those simply to buff their levy (as players did) was not great. Upon conquering an Island County of Pirate culture now, the building is destroy and cannot be built by you.

It's not a case of which is better, but one of which is best suited for what you're doing. Personally I would have most culture buildings locked to regional culture (since it's the people you're raising from in question who differ).

However, each culture has unique modifiers (I've been assigning it through static_modifiers.txt, ie giving the Ironborn better infantry but worse horses) for troops as is, so such buildings should play the role of buffing fort level, adding a few instances of a specific unit type or whatever you think should be used.

I'm also fairly certain you can allow a building to exist within the borders of a certain culture, and then use a separate block to prevent it from having any effects. Not sure how you would do that though.

**Comment by tannerflick4** [comment]
Thanks for the explanation! The location potential makes sense then.

**Comment by RowanMaBoot** [comment]
For special, unbuilt buildings could someone let me know when they were all historically built?

I may add an in-between 'under construction' state, but I also need to know for that when construction started (whether an approximation or known).

**--From Work**

**Comment by Vierwood** [comment]
Most of the unique buildings were built during the Age of Heroes. Only a few buildings and castles like Kings Landing, Dragonstone, The Eyrie, etc. Were built after the age of heroes.

**Comment by RowanMaBoot** [comment]
They're the ones I'm talking about when I say unbuilt structures. ;)

**--From Work**

**Comment by Vierwood** [comment]
Ughhh,

Coldmoat
Horn Hill
Oldstones
Mander Keep
Starpike
Sunspesr
The Eyrie 
The Bloody Gate
The Gates of the Moon
Runestone 
Moat Cailin

These are the ones I can think of off the top of my head.

**Comment by RowanMaBoot** [comment]
Yahp, ah know. Just need the dates (be it years or maybe month of the year) construction started and the day construction finished. :P

**--From Work**

**Comment by tannerflick4** [comment]
Coldmoat was raised by the Osgrey's during the Gardener Kings of the Reach, and another soure says it the Osgreys came around about 1000 years before The Conguest, so 6900-7100.

Horn Hill was built by 2 sons of Garth Greenhand (who was alive in the age of heroes) so probably in the 200s-300s.

Oldstones doesnt have any references to it before the Mudds.

Mander Keeps were built by the Gardener kings to guard the river, so probably early on for them.

Starpike was most likely around same time as Horn Hill, because Florys the Fox's son founded House Peake and she was a daughter of Garth Greenhand.

Sunspear itself was probably built after Nymeria's Invasion/Migration, but the Sandship had been there for a LOT longer, and Sunspear was built around it.

The Eyrie is most likely in 6700-7000, with it being built by Artys Arryn (the first Arryn)'s grandson when he believed the Gates of the Moon to be not "grand" enough. 

The Bloody Gate was built upon to its current state by Osric Arryn presumably in the 6900-7000 time, although a rougher "building" still existed before the Arryns came.

Gates of the Moon are larger than the Eyrie actually, and would be built by the first Arryns.

Runestone existed during the Andal Invasion, but no other idea on timing of its being built.

Moat Cailin is said by myth to exist thousands of years, and I think perhaps should exist in the Age of Heroes. Of course it should start to disintegrate around 7500 to represent the state its in the books.

Hope those help! I perused the ASOIAF wiki for these.
