### ISSUE TITLE
CRUNCH TIME

### ISSUE THREAD

**Issue by Vierwood** [Altemio/SevenKingdoms-master#17]
Seeing as the release is now only about 2 days away. We really need to hurry and finish a few features that we neglected to finish.

It's mainly just some history work that I need some help with.

- The Iron Islands history needs to be finished
- Dornish counts need to be created and landed 
- Title flags and CoAs still need to be assigned
- The Twins needs to reappear from thin air
- We need to find out how to remove all the buildings from the Dragonstone provinces
- Minor fixes
- Everyone should try to run the mod for about 50 years so we know it works (speed 5 is very fast)

Other than that we'll make the deadline. It's crunch time people.

**Comment by RowanMaBoot** [comment]
Speed 5 barely runs for me, but that is pretty consistent of any mod or game, including vanilla. However, I haven't had any issues. I did observe a while back Valyria turning into a nomadic horde. I think I may have fixed the problem, but I need confirmation as to whether or not it is still an issue.

To remove buildings from provinces, I would need to redo the building system and change tech. In theory I could make everything require at least level 1 tech to generate (not build), with the world using level 2/3, so that level 0 empires (yes empires) do not generate buildings. However the downside is that it would be.. Empire-wide. So the Dusklands would have no development at all.

I've started adding rivers. A pain in the arse to add, so let me know if there are any issues or if you guys think they look bad in one area or another.

**Comment by tannerflick4** [comment]
I can work on the counts for Dorne. Moved things IRL like a 8 hour meeting no one really needed to attend.

**Comment by Vierwood** [comment]
Also the Freehold always collapses within 50 or so years.

**Comment by tannerflick4** [comment]
But that should be a distinct possibility, honestly. It would allow for more things to happen with the free cities, and represents the viceory's power falling due to their not being a "home" liege.

**Comment by ZeroFighterR** [comment]
Thought you were working on the Iron Islands history vierwood. 

I can do that if you gave up on it. Currently still at work, but I shouldbe home in 4-5 hours

Whats the issue with the twins. I dont understand what you mean.. Missing building or what

**Comment by Vierwood** [comment]
I'm still working on the Iron Isles. Also the Freehold shouldn't fall within 50 years.

Also the building just isn't showing up in game. I don't even know if it's in the unique_buidings.txt

**Comment by RowanMaBoot** [comment]
Vierwood probably didn't add the building, so it isn't actually ingame. So in other words, the building needs to be added.

**Comment by tannerflick4** [comment]
Remember we do not need to hurry. This release is only an alpha and we have all the time in the world to mod everything in.

**Comment by tannerflick4** [comment]
Ok so Hellholt has its counts finished and Sunspear is in progress, probably around 50% done with its counts.

**Comment by RowanMaBoot** [comment]
A number of major issues should have since been solved. I've gone through even decision and event with a fine comb so hopefully all should be well. Basically a good time to start testing.

Localisation hasn't been adjusted for all of the events, but many unwanted events have been removed whilst many other events have been adjusted for our religions and cultures. Feedback would be appreciated as to how long-term stability fares.

Also, since reports have been rolling in if anyone could collate issues from localisation to whatever, putting them into a centralized issue soon would be a good idea. There has been some good reporting going on. Now, I've been at this all day so I need sleep!! ;)

**Comment by blackninja9939** [comment]
There will probably be a lot of localisation issues where you have not overwritten the customizable localisation fold so any vanilla localisation that references one of them will be checking for traits, religions and cultures etc. which no longer exist in the mod.
