### ISSUE TITLE
[TODO] Events & Mechanics

### ISSUE THREAD

**Issue by RowanMaBoot** [Altemio/SevenKingdoms-master#22]
Just some brainstorming. Any suggestions or ideas? Feel free to pop them here.

**The Rhoynar**

The Rhoynar were largely faced with a colossal threat - Valyria - and in time this threat marched against them. The fall of the Rhoynar lead to a number of historical events, including the exodus of the surviving Rhoynar to Westeros, specifically Dorne.

I'm not lore savvy, so those with better knowledge will need to supply dates and flavour for the event chain.

A simple event chain could go as follows:

- News of the Rhoynish Wars in the far East reaches Westeros.
- Rumours of great water magics used to combat and counter the fire and blood of Valyria.
- Talk of great Valyrian victories, but rumours of defeats.
- Rise of the Rhoynar army, numbering at least 250,000.
- Rhoynar slaughter 100,00 Valyrians, and strike down three dragons.

- Call Mother Valyria for help (leads to Rhoynar Exodus separate event chain).

OR

- Mother Valyria refuses to help (leads to Rhoynar surviving, possibly expanding or undermining the influence that Valyria has with the free cities)

**Comment by DeveloperAmr** [comment]
It would be highly unlikely for valyria to not help out since lore wise they destroyed them with 300 dragons and made the leader of the rhoynar watch as they burned their empire and it is said that the leader cursed the valyrian by calling to mother rhoyne and thus grayscale was created and killed many valyrians.

However the survivors lead by Nymeria had 10,000 ships of soldiers(which is in my opinion really overpowered if we remade it in-game so when I get around to doing this it will be enough to unite dorne and not just destroy everyone on the map.) Anyway everyone hated Nymeria except Morgan martell who married her and she conqured all of dorne and then when Morgan died she married some dude from house dayne and later house yornwood.

Personally the event chain ingeneral is the easy part the harder part is trying to balance it out since Nymeria although she is cool and all would be way to overpowered lorewise.

**Comment by DeveloperAmr** [comment]
It would be highly unlikely for valyria to not help out since lore wise they destroyed them with 300 dragons and made the leader of the rhoynar watch as they burned their empire and it is said that the leader cursed the valyrian by calling to mother rhoyne and thus grayscale was created and killed many valyrians.

However the survivors lead by Nymeria had 10,000 ships of soldiers(which is in my opinion really overpowered if we remade it in-game so when I get around to doing this it will be enough to unite dorne and not just destroy everyone on the map.) Anyway everyone hated Nymeria except Morgan martell who married her and she conqured all of dorne and then when Morgan died she married some dude from house dayne and later house yornwood.

Personally the event chain ingeneral is the easy part the harder part is trying to balance it out since Nymeria although she is cool and all would be way to overpowered lorewise.

**Comment by ZeroFighterR** [comment]
I just noticed this, but there's one thing where you're wrong Amr.

Nymeria led 10.000 ships, however some of them were lost on sea and several of them also followed someone else back to their land (leading into slavery or death). Most of the survivors however were not soldiers, but children, elderly and women. I'd say the number of people arriving in Sunspear is close around 5.000 (keep in mind that they have been attacked by pirates, corsairs, slavers and storms on sea and were sailing for several years).

Also the number of ships is most likely way less than said

**Comment by RowanMaBoot** [comment]
Well given the populations in the AGOT world, generally speaking, and the effects they had on the ethnic makeup of the Dornish, I'd say it was more than 5,000 people.

Even with 10 people a ship (and that is an incredibly low number), if only 1,000 ships made it to Dorne there would still be 10,000 people between those ships. Not to say GRRM thought about such specifics, and many of them may have had a barebones crew (for they were loaded with supplies, materials, food or livestock), but 10 people per ship really is a barebones number. You're not even talking about real ships with crews that small.

Several years at sea also seems a bit far fetched as we see travel in weeks to months in both the books and the TV series over such distances.

Best way to handle the Rhoynar would be through an aztec-invasion esque event (with further events that buff the development of land they take) I think, but it would expire fairly quickly and would be only applicable to one Kingdom in the region.

One cool thing we could do is allow them to arrive in different places.

**Comment by RowanMaBoot** [comment]
@Vierwood @tannerflick4 How is the Knightly Order doing, after the commit I pushed last night? Would test myself, but between sleep and work I've not had a chance yet - and if I'm pushing out further patches and fixes tonight I still might not be able to.

Basically requests for Knighthoods should be fixed now. Joining the Order should also be OK. And less Hedge Knight spam should be present.

**Comment by TitanRogue** [comment]
@Altemio 
What about a random Doom of Valyria? A dragon rider and his family seek refuge on Dragonstone. Then, 12 years later, the Freehold collapses and only few dragon lords survived it. The event could be deactivated by the game rules. We would need some new traits and a working dragon engine.

**Comment by DeveloperAmr** [comment]
So I went ahead and checked on the latest build, requesting knighthood works fine also joining doesnt seem like an issue. 

Request Knighthood descriptions need to be filled or removed since they are just 'request_knighthood_power_desc' 

Some conditions have the weird looking A before and after it. However nothing gamebreaking.

![20180727151239_1](https://user-images.githubusercontent.com/29560510/43318078-8191148e-91b0-11e8-82c6-b296216ebd85.jpg)
![20180727151600_1](https://user-images.githubusercontent.com/29560510/43318081-84a5f25c-91b0-11e8-8079-41dc8baebf18.jpg)

**Comment by RowanMaBoot** [comment]
@TitanRogue 
That'd be a great idea, I think! Ideally we'd want a minimum number of years before we see it, but we can have the mean time adjusted by the very same rule.

Also I'm working on a simple slavery system. Nothing too fancy and won't use actual characters. Got some good ideas and mechanically it seems to be good so far.

**Comment by RowanMaBoot** [comment]
@DeveloperAmr 
Thanks for the reports! Will take a look at them. Since Vier changed how the Ser knighting works, the events around joining that society probably need tweaking anyway since we still hand out a minor title, which I'm not sure if we need or use?
