### ISSUE TITLE
[TODO] Mechanics, Duel Engine. 

### ISSUE THREAD

**Issue by Madcliff** [Altemio/SevenKingdoms-master#27]
Currently, the duel engine needs unique customization to be fully initialized for Seven Kingdoms. This includes setting up unique attack types, and determining balance based on character traits and culture. currently needs the Jade Dragon patch to properly integrate weapons and equipment into the system to allow for proper scaling of abilities. Also needs the implementation of a dragon mechanic which is appropriate, to enable the proper relationship between dragons and foot combatants.

**Comment by TitanRogue** [comment]
Suggestions regarding the dragon engine:
The dragons are the power base of Valyria and its rulers. So loosing a dragon in combat or elsewise causes unlanded noble dragon riders to claim their titles if he doesn't have any other dragon left or has no dragon egg. When being "the plundering dragon" the dragon can be used on raids. You can offer the victim to hand out some money or to get burned alive. You get a new dragon conquest cb with a very big threat mutiplier in order to prefent realms from plopping. However, using a dragon in a war gives you an advantage but dragons can be killed.
There is only one efficient way to integrate dragons to the game and that is to make them real characters. The AGOT mod showed us that it works great but it is far too script-heavy. Making a lite version from scratch or porting the basic stuff like the siege and battle functions would be good equally, I guess. It surely depends on how much we actually want to port from other mods. I would start working on it if nobody already has.

**Comment by RowanMaBoot** [comment]
Madcliff / Zarathrustra (I've probably spelt that wrong) believes artifacts can be used in place of characters (or may eventually be used, if modding requests put forward are fulfilled down the line).

Plus, putting effort into creating a character driven dragon system isn't something we're particularly enthusiastic about given one already exists for AGoT (which we do not have permission to use obviously).

**Comment by TitanRogue** [comment]
@Altemio 
When we use artifacts the dragons won't have a personality. They'd be static objects hidden in the inventory. There wouldn't be any variety of dragons. We can use artifacts instead of characters but at cost of immersion and fun. And it isn't that much effort to create a basic "dragon engine" containing mechanics for sieges, battles, hatching and taming.
But I agree. If we decide to use a character driven dragon system we have to make an agreement with the AGOT team.
That's my opinion onthat subject.

**Comment by RowanMaBoot** [comment]
Zara was playing around with some ideas about giving them some personality, which is part of why we can't use artifacts right now, because it's just not feasible.

Although in all fairness, even character driven dragons don't per se have a huge amount of personality - or at least nothing we couldn't in theory add ourselves (naming of dragons is in the realm of possibility, or variable strength and size).

If we could get a really primitive event/character modifier based dragon system with basic dragon events, it'd be a good start and foundational for a more advanced system, be it character based or down the line artifact driven.

Hmmm.

**Comment by TitanRogue** [comment]
@Altemio 
I made a very basic character driven system (dragon portrait, some traits). If you want I can go ahead and finish it. We can use this system to add other creatures like direwolves or falcons,etc. too. It would be a great expansion. But if desired I can make artifact system.

Update:
I kept working on it and implemented a "strengtht" system. It can be used to calculate the outcome of dragon fights. But also to determine the end of their lifes. It depends on the dragons health, size (martial skills) and combat rating. If some values change the result will be recalculated each month. 
This can even work for artifacts.
![20180718003101_1](https://user-images.githubusercontent.com/40209082/42849278-d3593534-8a22-11e8-9d1f-7278ee105955.jpg)
![20180718003036_1](https://user-images.githubusercontent.com/40209082/42849284-d77d1ab8-8a22-11e8-9608-93d1c094828e.jpg)

**Comment by RowanMaBoot** [comment]
@TitanRogue 

Honestly that is quite awesome! If down the line Artifacts become a viable alternative (personality can be created through a number of methods, so that isn't a concern) then we can migrate and adapt any systems (if what Zara wants ever even becomes possible..).

If you want to make a character-driven dragon/creature/animal system then that is totally fine!

@Vierwood @tannerflick4 since I think both of you guys would be drooling over this. Or at least Vierwood.

**Comment by TitanRogue** [comment]
@Altemio 
Alright then, I'll finish the basics and extend it with direwolves, bears and some other creatures if I get the time. One thing that I'm a bit concerned about is the portrait stuff since we need to add new dragon. We need a source with "free license". I found some pretty cool dragons but I am not sure whether we can use them as they are described as unknown license. If anyone of you knows a website to get "free" artwork from let me know.

**Comment by tannerflick4** [comment]
Yeah adding personality driven creatures would be cool. I just know the AGOT system seems to work so well :)

**Comment by blackninja9939** [comment]
It is a cool system we have but it does come with its fair share of pain, making them not do things and screw things up is always a fun struggle...

**Comment by TitanRogue** [comment]
It surely is.But  I am making good progress. What about the life time? Right now a dragon has a chance of 66% to die at the age of 160.
