### ISSUE TITLE
Discord link created

### ISSUE THREAD

**Issue by tannerflick4** [Altemio/SevenKingdoms-master#29]
https://discord.gg/3WgSXKe

Join! :) This way we can talk about stuff without having to post them here

**Comment by RowanMaBoot** [comment]
We've actually got a public TeamSpeak I run, if anyone wants to discuss stuff on there. I personally don't have or use discord (due to personal preference, have a lot more control over TS compared to Discord, and more privacy).

I'll pop the IP for it here too, if anyone is interested in chatting there too (you can usually find me there, in the lower depths of the lair of corruption, playing various games with other people).

ts.rccclan.com
