### ISSUE TITLE
ACOK/ASOS Bookmark

### ISSUE THREAD

**Issue by Vierwood** [Altemio/SevenKingdoms-master#31]
Seeing that the AGOT mod decided to make their own version of our scenarios, Rowan has given me the greenlight to begin preliminary work on our own Game of Thrones bookmark. It'll take awhile, but I'll try to get as much of it done as possible. Help would be appreciated.

**Comment by tannerflick4** [comment]
I'll gladly help too.

**Comment by RowanMaBoot** [comment]
Not exactly, as said prior I have neither the time nor the desire to moderate what bookmarks are created (was stricter prior as I believed no direct competition in that regard beyond the current level would be good, but I guess it is what it is now), however I still do not believe such a date is in the interest of TSK.

For starters, our current bookmarks are not even remotely polished and aren't strictly speaking playable either. Then we've got countless errors and the sort to fix, and then finally actual playable content.

(currently 480 miles into a 1000 mile journey, no pc access for a couple of weeks)

**Comment by blackninja9939** [comment]
We started working on those scenarios in 2014

**Comment by Vierwood** [comment]
@blackninja9939 the new bookmarks aren't exactly polished that well.

I'm going on vacation and will be back in about a week. When I get back I'll power through the history of Braavos, Andalos, and Pentos.

**Comment by blackninja9939** [comment]
Didn't say it was continuous work mostly a bit here and there until the guy who started it got a break to work more on them in the past few months. But to imply that we stole" your scenarios to make our own versions of is ridiculous on the grounds we started on them and the mod way before you guys

**Comment by tannerflick4** [comment]
Lol everyone calm down. And Vier, we dont need you to "power through"
things - I HATE it when people rush. We will get there when we get there.

But we do need to make sure this mod actually runs before we keep adding
too much other stuff.

**Comment by Vierwood** [comment]
@blackninja9939 I never said that you stole the bookmark. I'm sorry if I accidentally implied it.

@tannerflick4 I seem to get the most done whenever I'm able to find a long period of free time. I'm currently not at school because of Winter Break, so I have the time to go ahead and do it.

**Comment by RowanMaBoot** [comment]
There is already overlap given our mods are set in the same universe, and given the fact 'our' bookmarks are canon, it isn't a surprise or an issue if AGoT has overlap in that regard, in my humble opinion.

The mods differ in playstyle considerably, and they will continue to play differently (perhaps more so with time). Our map alone assures such - we won't ever be able to reflect the world state in later bookmarks (have trouble even now, to be honest, but Jade Dragon will help in that regard), which is largely why I don't want to touch them.

Think of it this way; if people play and enjoy the new bookmarks in AGoT, they may find our mod super enjoyable. If they don't, then no biggy.

I want our mod to do what we aim for it to do very well, rather than trying to have a billion bookmarks and attempting to compete directly against AGoT. To be quite blunt, we don't have the people to do that even if we wanted to.

I'd write more, but i'm with my (very ill) grandmother at the moment, so I hope my point got across without sounding like an arse.

**Comment by tannerflick4** [comment]
Yep. I agree exactly, although it gives more potential for us way down the
road. I am just concerned with no one "cramming" just to add stuff.

**Comment by blackninja9939** [comment]
Competing is unlikely to be something that will crop up, what you guys really need is to add in actual content. Currently there is extremely little event and decisions etc. which leaves mostly just the new map. 


Having lots of more granular cultures and title setup means nothing if there are no events outside of vanilla ones to go with any of that so after fixing the error log that would be a good place to start as otherwise you can cover every single time period but if they all play identically to vanilla then it is a bit of a waste of time as there will invariably be a handful of bookmarks played the most anyway.

**Comment by RowanMaBoot** [comment]
Yeah, as many users have said - some like this about our mod but many do not - our mod is CK2 in the AGOT universe, whilst your mod is the AGOT universe in CK2.

It's a pretty significant and a very true distinction, because our mod plays like a re-skinned CK2 because that is exactly what it is. That'll change with time and development, but no matter how many bookmarks, dynasties, characters, wars, vassals and the sort we add it'll stay a re-skinned CK2 - events and custom mechanics will be what we need to focus on for it to not be the case.
