### ISSUE TITLE
Terrain gets destroyed

### ISSUE THREAD

**Issue by Sqoops** [Altemio/SevenKingdoms-master#43]
![agot](https://user-images.githubusercontent.com/4706311/62422739-864d6400-b6b7-11e9-973d-bc57f36ff23c.jpg)

**Comment by TitanRogue** [comment]
Yeah, noticed the same issue with my dragon events. It requires a more or less complex syntax to get fixed. I think it is easier to make terrain a province modifier.

**Comment by RowanMaBoot** [comment]
So the reason the 'terrain building' is a building is so that it can have more effects - fort level being one of the main ones, otherwise we can fall back to the old method of using modifiers within the terrain_type itself.

However, we could create a scripted trigger with the terrain buildings listed (it would be an OR = {buildings} statement, then quickly find any events that destroy buildings - then add a NOT = {non_lootable_building_trigger} to the building in barony scope to avoid destroying those buildings.

**Comment by TitanRogue** [comment]
@Altemio 
You can use every modifier as province modifiers, I checked it.

**Comment by RowanMaBoot** [comment]
@TitanRogue ah that is good to know. Previously the fort_level could be used on a province level, but had no effect. I'll trial it out and will remove the landscape buildings if it works as desired!

**Comment by RowanMaBoot** [comment]
Closing this issue; terrain modifiers replaced the buildings.
